### ISSUE TITLE
composer install error 

### ISSUE THREAD

**Issue by denghongcai** [fremail/lumen-nested-route-groups#1]
``` bash
  [InvalidArgumentException]                                                                                                                                         
  Could not find package fremail/lumen-nested-route-groups at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  

```

**Comment by AntonDemushkin** [comment]
When you have tried to require the package, it has a minimum-stability: dev. You had a minimum-stability: stable.

Now I updated the minimum-stability of the package to beta and updated the readme.
To install this package you need to change minimum-stability in the composer.json file in your project. Look at updated instractions here: https://github.com/fremail/lumen-nested-route-groups/blob/master/readme.md#how-to-install

Let me know about any troubles with installing or using this package.
