### ISSUE TITLE
Any not working

### ISSUE THREAD

**Issue by Sofianio** [fremail/lumen-nested-route-groups#6]
the route $app->any(...) isn't working.
if it's not supposed to work then please add it :)

thanks.

**Comment by AntonDemushkin** [comment]
This library extends the Lumen routing only by one function - `$app->group(...)`. 

Lumen doesn't support `$app->any(...)`.
But... I can add it.
And it'd be better because this `$app->any(...)` function is very powerful.

**Comment by Sofianio** [comment]
Thanks a lot man, I'll be waiting for the next release.

**Comment by AntonDemushkin** [comment]
@Sofianio I glad to say that the `$app->any()` and `$app->match()` methods are ready to use starting from [v1.1.0](https://github.com/fremail/lumen-nested-route-groups/releases/tag/v1.1.0)!

**Comment by Sofianio** [comment]
Nice, very nice 💯, thank you very much.
keep up the good work :)
